appenders:
  console:
    kind: console
    encoder:
      # pattern: "{d(%Y-%m-%d %H:%M:%S)} {M} {f}:{L} {h({l})} - {m}\n"
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)})} {h({f}:{L})} {h({l})} {h(- {m})}\n"
    filters:
      - kind: threshold
        level: trace
  # file:
  #   kind: file
  #   path: log/output.log
  #   encoder:
  #     # no date: not needed during development
  #     pattern: "{d(%H:%M:%S)} {f}:{L} {l} - {m}\n"
  #     # pattern: "{d(%Y-%m-%d %H:%M:%S)} {f}:{L} {l} - {m}\n"

  #   append: false
  #   filters:
  #     - kind: threshold
  #       level: trace

# root:
#   level: error
#   appenders:
#     - console
#     - file

loggers:
  base:
    level: trace
    appenders:
      - console
      # - file
  mbase:
    level: trace
    appenders:
      - console
      # - file

  network-test-util:
    level: trace
    appenders:
      - console
      # - file 
